#!/bin/bash

ICAFILE='/tmp/IE8.ica'

cat > ${ICAFILE} << EOF
[Encoding]
InputEncoding=UTF8

[WFClient]
CPMAllowed=On
ClientName=WI_Rp8zh2a0bnYq13fp2
ProxyFavorIEConnectionSetting=Yes
ProxyTimeout=30000
ProxyType=Auto
ProxyUseFQDN=Off
RemoveICAFile=yes
TransparentKeyPassthrough=Local
TransportReconnectEnabled=On
VSLAllowed=On
Version=2
VirtualCOMPortEmulation=Off

[ApplicationServers]
Internet Explorer 8=

[Internet Explorer 8]
Address=10.90.14.79:1494
AutologonAllowed=ON
BrowserProtocol=HTTPonTCP
CGPAddress=*:2598
ClearPassword=E499A9DC985569
ClientAudio=On
DesiredColor=8
DesiredHRES=1024
DesiredVRES=768
DoNotUseDefaultCSL=On
Domain=\9FB5B9044DFA53A0
FontSmoothingType=0
InitialProgram=#Internet Explorer 8
LPWD=156
Launcher=WI
LocHttpBrowserAddress=!
LogonTicket=E499A9DC9855699FB5B9044DFA53A0
LogonTicketType=CTXS1
LongCommandLine=
NRWD=141
ProxyTimeout=30000
ProxyType=Auto
SFRAllowed=Off
SSLEnable=Off
SessionsharingKey=-0OvdwZi4HKB6ibbzFKAMHD
StartIFDCD=1438696276475
StartSCD=1438696276475
TRWD=15
TWIMode=On
Title=Internet Explorer 8
TransportDriver=TCP/IP
UILocale=en
WinStationDriver=ICA 3.0

[Compress]
DriverNameWin16=pdcompw.dll
DriverNameWin32=pdcompn.dll

[EncRC5-0]
DriverNameWin16=pdc0w.dll
DriverNameWin32=pdc0n.dll

[EncRC5-128]
DriverNameWin16=pdc128w.dll
DriverNameWin32=pdc128n.dll

[EncRC5-40]
DriverNameWin16=pdc40w.dll
DriverNameWin32=pdc40n.dll

[EncRC5-56]
DriverNameWin16=pdc56w.dll
DriverNameWin32=pdc56n.dll
EOF


/opt/Citrix/ICAClient/wfica ${ICAFILE}
