#!/bin/bash

ICAFILE='/tmp/IE8.ica'

cat > ${ICAFILE} << EOF
[Encoding]
InputEncoding=UTF8

[WFClient]
CPMAllowed=On
ClientName=WI_Ywq-s_lIQsK8mlHm-
ProxyFavorIEConnectionSetting=Yes
ProxyTimeout=30000
ProxyType=Auto
ProxyUseFQDN=Off
RemoveICAFile=yes
TransparentKeyPassthrough=Local
TransportReconnectEnabled=On
VSLAllowed=On
Version=2
VirtualCOMPortEmulation=Off

[ApplicationServers]
IE 8=

[IE 8]
Address=10.50.10.227:1494
AutologonAllowed=ON
BrowserProtocol=HTTPonTCP
CGPAddress=*:2598
ClearPassword=08D3F264475F8F
ClientAudio=Off
DesiredColor=8
DoNotUseDefaultCSL=On
Domain=\FAEE21496F76DD25
FontSmoothingType=0
InitialProgram=#IE 8
LPWD=266
Launcher=WI
LocHttpBrowserAddress=!
LogonTicket=08D3F264475F8FFAEE21496F76DD25
LogonTicketType=CTXS1
LongCommandLine=
NRWD=63
ProxyTimeout=30000
ProxyType=Auto
SFRAllowed=Off
SSLEnable=Off
ScreenPercent=75
SessionsharingKey=-3VapdLoH1eY5bmevOKBvuA
StartIFDCD=1387211520610
StartSCD=1387211520610
TRWD=203
TWIMode=On
Title=IE 8
TransportDriver=TCP/IP
UILocale=en
WinStationDriver=ICA 3.0

[Compress]
DriverNameWin16=pdcompw.dll
DriverNameWin32=pdcompn.dll

[EncRC5-0]
DriverNameWin16=pdc0w.dll
DriverNameWin32=pdc0n.dll

[EncRC5-128]
DriverNameWin16=pdc128w.dll
DriverNameWin32=pdc128n.dll

[EncRC5-40]
DriverNameWin16=pdc40w.dll
DriverNameWin32=pdc40n.dll

[EncRC5-56]
DriverNameWin16=pdc56w.dll
DriverNameWin32=pdc56n.dll
EOF

/opt/Citrix/ICAClient/wfica ${ICAFILE}
