#!/bin/sh

# Do nothing on Macs...
if [[ x$(uname -s) == xDarwin ]]; then
    exit 0
fi


# This temporarily remaps the CapsLock key to a Control key.
# The keyboard will return to the previous settings after a
# reboot. The Linux console and the X Window system each
# handles keypresses separately, so each must be remapped
# separately. First remap the X keyboard since this does not
# require root access.

# Remap the CapsLock key to a Control key for
# the X Window system.
if type setxkbmap >/dev/null 2>&1; then
    setxkbmap -layout us -option ctrl:nocaps 2>/dev/null
fi

# You have to be root to remap the console keyboard.
# if [ "$(id -u)" != "0" ]; then
    # echo "This script is not running as root so the console CapsLock cannot be remapped."
    # echo "Perhaps you forgot to run this under sudo. Note that this problem does not effect X."
    # echo "This only effects the consoles running on Alt-f1 through Alt-f6."
    # exit 2
# fi
# Remap the CapsLock key to a Control key for the console.
(sudo dumpkeys | grep keymaps; echo "keycode 58 = Control") | sudo loadkeys
