#!/bin/bash

ICAFILE='/tmp/vSphere.ica'

cat > ${ICAFILE} << EOF
[Encoding]
InputEncoding=UTF8

[WFClient]
CPMAllowed=On
ClientName=WI_HJslO0inRp5_ygdKI
ProxyFavorIEConnectionSetting=Yes
ProxyTimeout=30000
ProxyType=Auto
ProxyUseFQDN=Off
RemoveICAFile=yes
TransparentKeyPassthrough=Local
TransportReconnectEnabled=On
VSLAllowed=On
Version=2
VirtualCOMPortEmulation=Off

[ApplicationServers]
VMware vCenter Converter Standalone=

[VMware vCenter Converter Standalone]
Address=10.50.13.239:1494
AutologonAllowed=ON
BrowserProtocol=HTTPonTCP
CGPAddress=*:2598
ClearPassword=55E19E48756588
ClientAudio=Off
DesiredColor=8
DesiredHRES=1024
DesiredVRES=768
DoNotUseDefaultCSL=On
Domain=\4A8799CD0F006472
FontSmoothingType=0
InitialProgram=#VMware vCenter Converter Standalone
LPWD=140
Launcher=WI
LocHttpBrowserAddress=!
LogonTicket=55E19E487565884A8799CD0F006472
LogonTicketType=CTXS1
LongCommandLine=
NRWD=93
ProxyTimeout=30000
ProxyType=Auto
SFRAllowed=Off
SSLEnable=Off
SessionsharingKey=-0OvdwZi4HKB6ibbzFKAMHD
StartIFDCD=1405446531805
StartSCD=1405446531805
TRWD=47
TWIMode=On
Title=VMware vCenter Converter Standalone
TransportDriver=TCP/IP
UILocale=en
WinStationDriver=ICA 3.0

[Compress]
DriverNameWin16=pdcompw.dll
DriverNameWin32=pdcompn.dll

[EncRC5-0]
DriverNameWin16=pdc0w.dll
DriverNameWin32=pdc0n.dll

[EncRC5-128]
DriverNameWin16=pdc128w.dll
DriverNameWin32=pdc128n.dll

[EncRC5-40]
DriverNameWin16=pdc40w.dll
DriverNameWin32=pdc40n.dll

[EncRC5-56]
DriverNameWin16=pdc56w.dll
DriverNameWin32=pdc56n.dll
EOF

/opt/Citrix/ICAClient/wfica ${ICAFILE}
