#!/usr/bin/bash

#passwdfile="${HOME}/.dotfiles/.vncpasswd"
x2x="/usr/local/bin/x2x"
ssh='/bin/ssh'
target="optiplex790.nyhq.nytint.com"
port=22

nc -w 5 ${target} ${port} <<< "0" || (echo "Error: Couldn't connect." ;  exit 1)

#if ! [[ -f ${passwdfile} ]]; then
#    printf "Error: No password file \"%s\"\n" ${passwdfile}
#    exit 1
#fi

num=$(pgrep -f xdaemon | wc -l )
echo $num
if [[ $num > 2 ]]; then
    echo 'Daemon already running. Exiting.'
    exit 1
fi


while :; do
    ${ssh} -t ${target} ${x2x} -to :0 -west
    sleep 2
done
